apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: worm-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "worm-controller.labels" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      {{- include "worm-controller.selectorLabels" . | nindent 6 }}
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
            app.kubernetes.io/name: worm-worker
      toPorts:
        - ports:
            - port: "8081"
              protocol: TCP
  egress:
    - toEntities: [kube-apiserver]
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
