apiVersion: v1
kind: ServiceAccount
metadata:
  name: worm-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "worm-controller.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: worm-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "worm-controller.labels" . | nindent 4 }}
rules:
  - apiGroups: ["lab.experiments.io"]
    resources: ["worms"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["lab.experiments.io"]
    resources: ["worms/status"]
    verbs: ["get", "patch", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames: [{{ .Values.worm.workerDeploymentName | quote }}]
    verbs: ["get"]
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    resourceNames: [{{ .Values.worm.workerDeploymentName | quote }}]
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: worm-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "worm-controller.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: worm-controller
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: worm-controller
