apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: worm-regression
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: bounded-worm-lab
    app.kubernetes.io/managed-by: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Schywi/experiments.git
    targetRevision: trackc
    path: apps/regression/chart
    helm:
      releaseName: worm-regression
  destination:
    server: https://kubernetes.default.svc
    namespace: worm-lab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
