image:
  repository: docker.io/local/worm-worker
  tag: tilt
  pullPolicy: IfNotPresent

replicaCount: 1

controller:
  url: http://worm-controller.worm-lab.svc.cluster.local:8081

sampleIntervalMilliseconds: 1000

resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 32Mi
