apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: worm-regression
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "worm-regression.labels" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      {{- include "worm-regression.selectorLabels" . | nindent 6 }}
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
            app.kubernetes.io/name: vector
      toPorts:
        - ports:
            - port: "4000"
              protocol: TCP
