apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: worm-regression
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: bounded-worm-lab
    app.kubernetes.io/managed-by: argocd
    experiments.io/ownership: argocd-stable
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Schywi/experiments.git
    targetRevision: 592d7f531aa4b51b9c1bb0e28b8180717a15a7ec
    path: apps/regression/chart
    helm:
      releaseName: worm-regression
      parameters:
        - name: image.tag
          value: dc3e359
  destination:
    server: https://kubernetes.default.svc
    namespace: worm-lab
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
