apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: worm-vector
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: bounded-worm-lab
    app.kubernetes.io/managed-by: argocd
    experiments.io/ownership: argocd-stable
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Schywi/experiments.git
    targetRevision: 592d7f51cdb71416dd5261868b39a1046be96b15
    path: config/vector
    helm:
      releaseName: worm-vector
  destination:
    server: https://kubernetes.default.svc
    namespace: worm-lab
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
