apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-datasources
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: {{ .Values.datasource.name }}
        uid: {{ .Values.datasource.uid }}
        type: prometheus
        access: proxy
        url: {{ .Values.datasource.url }}
        isDefault: true
        jsonData:
          httpMethod: POST
          timeInterval: {{ .Values.datasource.timeInterval }}
