apiVersion: v1
kind: ResourceQuota
metadata:
  name: worm-worker-cap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "worm-worker.labels" . | nindent 4 }}
spec:
  hard:
    requests.memory: 640Mi
    limits.memory: 640Mi
